## Une stratégie de jeu basé sur l'aléa. 
### On propose de jouer à un jeu de manière aléatoire et d'en déduire des probabilités de gains par rapport à ces stratégies.
### On construit ensuite des stratégies qui utilisent ces estimations aléatoires qui sont meilleures qu'une stratégie aléatoire.

In [1]:
## import des librairies pour calcul et représentation graphique.
import numpy as np
import pylab as pl
from random import shuffle,choices
import torch as torch
import torch.nn as nn

### Pour coder le jeu de morpion, on peut représenter la grille de jeu comme une matrice de taille $3 \times 3$. Les deux joueurs choisissent chacun à leur tour une position sur cette matrice. Le premier qui parvient à aligner trois positions en ligne, en colonne ou en diagonale a gagné. On représente l'ensemble des cases non utilisées par une liste.


In [2]:
### par exemple, on encode ici la liste des coordonnées au début du jeu.
ensemble_des_etats = []
for i in range(3):
    for j in range(3):
        ensemble_des_etats.append((i,j))
print(ensemble_des_etats)

[(0, 0), (0, 1), (0, 2), (1, 0), (1, 1), (1, 2), (2, 0), (2, 1), (2, 2)]


### Sur un jeu comme le morpion qui est relativement simple, on peut développer l'arbre des possibilités de jeu.

### **<font color="red">Question 1: </font>** Donner une majoration du nombre de parties possibles. On pourrait donc développer l'arbre et trouver le meilleur coup à jouer. 

### On souhaite procéder différemment en explorant des stratégies générées de manières aléatoires ce qui peut avoir un intérêt dans des situations plus complexes.

### Pour encoder le jeu, on associe à chaque joueur la liste des positions choisies. On peut ensuite représenter la grille de jeu.

In [3]:
### par exemple: 
liste_1 = [(0,0)] # le joueur 1 a joué en position 0,0
liste_2 = [(1,1)] # le joueur 2 a joué en position 1,1
### on définit une fonction qui permet de représenter la matrice de jeu.
def encode_state(liste_1,liste_2):
    result = np.zeros((3,3))
    for z in liste_1:
        result[z[0],z[1]]=1
    for z in liste_2:
        result[z[0],z[1]]=-1
    return result
print(encode_state(liste_1,liste_2))
print("Les 1 repéresentent les positions choisies par le joueur 1, les -1 celles du joueur 2, les 0 les positions qui n'ont pas été utilisées.")

[[ 1.  0.  0.]
 [ 0. -1.  0.]
 [ 0.  0.  0.]]
Les 1 repéresentent les positions choisies par le joueur 1, les -1 celles du joueur 2, les 0 les positions qui n'ont pas été utilisées.


### On définit une fonction pour évaluer si étant donnée une liste de positions (par exemple la liste de positions choisies par le joueur 1) le joueur a gagné.

In [4]:
def select(i):
    def f(x):
        return x[i]
    return f

def diag(x):
    return 1*(x[0]==x[1])

def antidiag(x):
    return 1*(x[1]==2-x[0])

def evaluation_victory(liste):
    result = None
    for i in range(2):
        if list(map(select(i),liste)).count(0)==3:
            return True
        if list(map(select(i),liste)).count(1)==3:
            return True
        if list(map(select(i),liste)).count(2)==3:
            return True
        if sum(list(map(diag,liste)))==3:
            return True
        if sum(list(map(antidiag,liste)))==3:
            return True
    return result
liste_1 =[(0,0),(0,1),(0,2)] ## liste de positions gagnantes
liste_2 = [(1,0),(0,1),(0,2)] ## liste de positions perdantes
print("le joueur avec la liste 1 a-t-il gagné? ",evaluation_victory(liste_1))
print("le joueur avec la liste 2 a-t-il gagné? ",evaluation_victory(liste_2))

le joueur avec la liste 1 a-t-il gagné?  True
le joueur avec la liste 2 a-t-il gagné?  None


### On propose de considérer une stratégie pour chaque joueur qui est complètement aléatoire. C'est-à-dire que chaque joueur choisit uniformément aléatoirement entre les positions disponibles. 
### Cette stratégie est évidemment stupide, mais on souhaite répondre à la question suivante: Pour ce couple de stratégies aléatoires, est-il plus avantageux de jouer en premier ou en second?

### **<font color="red">Question 2: </font>** Implémenter une partie aléatoire. 


In [2]:
def random_play(current_state=None,liste_1 = None,liste_2 = None):
    ## tant que la partie n'est pas terminée, les joueurs jouent de manière aléatoire
    ## on utilisera seulement la fonction shuffle qui permute aléatoirement un liste donnée en argument.
    ## on pourra insérer en argument les listes déjà choisies des joueurs.
    return None ### on retournera le numéro du vainqueur, joueur 1 ou 2 et la liste de positions de ce joueur et de son adversaire.



liste_1 =[(0,0),(0,1),(0,2)] ## liste de positions gagnantes
liste_2 = [(1,0),(1,1),(1,2)]
random_play()

### **<font color="red">Question 3: </font>** Estimer la probabilité de gagner du joueur 1, celle du joueur 2, celle de finir à égalité. Pour cela, on utilisera la méthode de Monte-Carlo. Déterminer le nombre de tirage nécessaires pour avoir une précision de 0.01 sur la probabilité estimée dans l'intervalle de confiance donnée par la méthode de Monte-Carlo.

In [3]:
### définir une fonction qui prend en argument les listes de positions des joueurs, et estimer par la 
### méthode de Monte-Carlo les probabilités de gains et de partie nulle.
### Pour savoir à partir des listes qui doit jouer, il suffit de regarder la longueur des deux listes. 
### Si les longueurs sont égales c'est le tour du joueur 1, sinon c'est le tour du joueur 2. Par convention, la
### la première liste donnée est celle du joueur 1 et la seconde celle du joueur 2.

def MC_estimate(n_tirages,current_state,liste_1,liste_2):
    return None ### (proba_gain_1,proba_gain_2,proba_nul)

MC_estimate(100,None,[],[])

### On souhaite évaluer la probabilité de gain d'un choix de case. Pour cela, pour on utilisera la méthode de MC, pour chaque choix possible de mouvement pour un des joueurs.
### **<font color="red">Question 4: </font>** Implémenter une fonction qui permet d'évaluer la probabilité de gain pour un choix donné, qui prend en argument la liste des positions du joueur 1, du joueur 2 et celles restantes disponibles dans le jeu. Implicitement en fonction des listes des joueurs, ce qu'on estime est la probabilité de gain pour un choix du joueur qui doit jouer.


In [4]:
def evaluate_strategy(moves,current_state,liste_1,liste_2):
    probabilities = []

    return probabilities

### **<font color="red">Question 5: </font>** Implémenter une stratégie qui consiste à sélectionner le choix qui a la plus grande probabilité de gain face à un adversaire complètement aléatoire.

In [5]:
def random_play_with_estimates():

    return None
random_play_with_estimates()

### **<font color="red">Question 6: </font>** Implémenter une fonction qui permet de jouer contre la méthode implémentée précédemment, c'est-à-dire qui estime la probabilité de gain d'un mouvement sur des stratégies complètement aléatoire.

In [6]:
def play_against_MC():
    return None
   

In [7]:
play_against_MC()

### **<font color="red">Question 7: </font>** Implémenter une stratégie qui suppose que l'adversaire utilise la stratégie implémentée dans les questions précédentes et qui vise à maximiser sa probabilité de gain.